name: Publish packages

on:
  push:
    tags: ["*"]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  npm:
    uses: tree-sitter/workflows/.github/workflows/package-npm.yml@216133f5cb4469b112c5e83415869e58b25c353a
    with:
      grammars: apex soql sosl
    secrets:
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
