name: Test full

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Use Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          cache: npm
          node-version: 20
      - name: Npm install node-gyp-build
        run: |
          npm i node-gyp-build
      - name: Npm install
        run: |
          npm ci
      - name: Unit tests
        run: |
          npm test
